import './global.css';
import type { Viewport } from 'next';
import { Providers } from './providers';
import AppHeader from '../components/app-header/app-header';
import clsx from 'clsx';
import { Inter as FontSans } from 'next/font/google';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
};

export const metadata = {
  title: 'Welcome to cs-test',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: // modal,
{
  children: React.ReactNode;
  // modal: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={clsx(
          'min-h-screen bg-background font-sans antialiased ',
          fontSans.variable
        )}
      >
        <Providers>
          <div className="relative flex flex-col h-screen md:min-w-md">
            <AppHeader />
            <main className="container mx-auto max-w-xl pt-16 px-6 flex-grow">
              {children}
            </main>
            {/* {modal}
            <div id="modal-root" /> */}
          </div>
        </Providers>
      </body>
    </html>
  );
}
